#+TITLE: Marco Paganoni
#+OPTIONS: toc:nil num:nil
#+HTML_HEAD_EXTRA: <style>body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif}</style>

* About

I am a Ph.D. student in Formal Verification at the Università della Svizzera
italiana (USI) in Lugano, Switzerland, working on the deductive verification of
JVM bytecode programs under the supervision of Prof. Carlo Alberto Furia.

* Contact

- Email :: [[mailto:paganma@usi.ch][paganma@usi.ch]]
- GitHub :: [[https://github.com/paganma][github.com/paganma]]

* Education

- 2022–present :: Ph.D., Università della Svizzera italiana, Lugano, Switzerland. Deductive verification of JVM bytecode programs, supervised by Prof. Carlo Alberto Furia.
- 2020–2022 :: M.Sc. in Software and Data Engineering, Università della Svizzera italiana, Lugano, Switzerland.
- 2017–2020 :: B.Sc. in Informatics, Università della Svizzera italiana, Lugano, Switzerland.

* Experience

- 2022–present :: Teaching Assistant, Università della Svizzera italiana, Lugano, Switzerland. Assistance for the Software Design & Modeling and Software Analysis courses.
- Sep–Dec 2019 :: Software Developer, Hoxell, Lugano, Switzerland. Setup application of the hotel management system (PHP/Laravel).
- Jun–Aug 2016 :: Software Developer, Globo S.r.l., Bergamo, Italy. GIS application for converting cadastral data (Python/QGIS).

* Projects

- ByteBack :: A deductive verification tool for JVM bytecode ([[https://github.com/atom-sw/byteback][github.com/atom-sw/byteback]]).
- Clontrol :: A delimited continuations library for Clojure on the JVM ([[https://github.com/paganma/clontrol][github.com/paganma/clontrol]]).
- BCC :: A model-based testing framework for the Boogie intermediate verification language ([[https://github.com/paganma/boogie-consistency-checker][github.com/paganma/boogie-consistency-checker]]).

* Publications

#+bibliography: ./bibliography.bib
#+cite_export: csl springer-lncs.csl

[cite/n:@*]

#+print_bibliography:
